---
ledger:
  Armor:
    fields:
    - name: Name
    - name: Conceal
      type: boolean
    - name: Rating
    - name: Strength
    - name: Defense
    - name: Speed
    - name: Availability
    - name: Coverage
    - name: Book
    - name: Page
    templates:
    - name: Bomb Suit
      era: Modern
      conceal: false
      rating: 4/6
      strength: 3
      defense: -5
      speed: -4
      availability: 5
      coverage: Torso, arms, head
      book: Hurt Locker
      page: 142
    - name: Chainmail
      era: Archaic
      conceal: false
      rating: 3/1
      strength: 3
      defense: -2
      speed: -2
      availability: 2
      coverage: Torso, arms
      book: Chronicles of Darkness
      page: 270
    - name: Flak Jacket
      era: Modern
      conceal: false
      rating: 2/4
      strength: 1
      defense: -1
      speed: 0
      availability: 2
      coverage: Torso, arms
      book: Chronicles of Darkness
      page: 270
    - name: Full Riot Gear
      era: Modern
      conceal: false
      rating: 3/5
      strength: 2
      defense: -2
      speed: -1
      availability: 3
      coverage: Torso, arms, legs
      book: Chronicles of Darkness
      page: 270
    - name: Helmets
      era: Modern, Archaic
      conceal: false
      rating: Special
      strength: 2
      defense: -1
      speed: 0
      availability: 3
      coverage: Head
      book: Hurt Locker
      page: 142
    - name: Kevlar Vest
      era: Modern
      conceal: true
      rating: 1/3
      strength: 1
      defense: 0
      speed: 0
      availability: 1
      coverage: Torso
      book: Chronicles of Darkness
      page: 270
    - name: Leather (hard)
      era: Archaic
      conceal: false
      rating: 2/0
      strength: 2
      defense: -1
      speed: 0
      availability: 1
      coverage: Torso, arms
      book: Chronicles of Darkness
      page: 270
    - name: Lorica Segmentata
      era: Archaic
      conceal: false
      rating: 2/2
      strength: 3
      defense: -2
      speed: -3
      availability: 4
      coverage: Torso
      book: Hurt Locker
      page: 142
    - name: Plate
      era: Archaic
      conceal: false
      rating: 4/2
      strength: 3
      defense: -2
      speed: -3
      availability: 4
      coverage: Torso, arms, legs
      book: Chronicles of Darkness
      page: 270
    - name: Reinforced Clothing
      era: Modern
      conceal: true
      rating: 1/0
      strength: 1
      defense: 0
      speed: 0
      availability: 1
      coverage: Torso, arms, legs
      book: Chronicles of Darkness
      page: 270
    - name: Sports Gear
      era: Modern
      conceal: false
      rating: 2/0
      strength: 2
      defense: -1
      speed: -1
      availability: 1
      coverage: Torso, arms, legs
      book: Hurt Locker
      page: 142
